import React from 'react';
import {
  History,
  Map,
  Scale,
  Globe,
  BookOpen,
  Plus,
  Trash2,
  ChevronRight,
  ChevronLeft,
  CheckCircle,
  XCircle,
  BrainCircuit,
  LogOut,
  User,
  Settings,
  Menu,
  X,
  Clock,
  Trophy,
  Target,
  ArrowLeft,
  Sun,
  Moon,
  BarChart3,
  Zap,
  Award,
  Star,
  Eye,
  Sparkles,
  Home,
  GraduationCap,
  TrendingUp,
  Shield,
  Play,
  RotateCcw,
  Hash,
  Timer,
  CircleCheck,
  CircleX,
  Minus,
  FileQuestion,
  Layers,
  PenLine,
  Flag,
} from 'lucide-react';

export const Icon = ({ name, className }: { name: string, className?: string }) => {
  const icons: Record<string, React.ReactNode> = {
    History: <History className={className} />,
    Map: <Map className={className} />,
    Scale: <Scale className={className} />,
    Globe: <Globe className={className} />,
    BookOpen: <BookOpen className={className} />,
    Plus: <Plus className={className} />,
    Trash: <Trash2 className={className} />,
    ChevronRight: <ChevronRight className={className} />,
    ChevronLeft: <ChevronLeft className={className} />,
    CheckCircle: <CheckCircle className={className} />,
    XCircle: <XCircle className={className} />,
    Brain: <BrainCircuit className={className} />,
    LogOut: <LogOut className={className} />,
    User: <User className={className} />,
    Settings: <Settings className={className} />,
    Menu: <Menu className={className} />,
    X: <X className={className} />,
    Clock: <Clock className={className} />,
    Trophy: <Trophy className={className} />,
    Target: <Target className={className} />,
    ArrowLeft: <ArrowLeft className={className} />,
    Sun: <Sun className={className} />,
    Moon: <Moon className={className} />,
    BarChart3: <BarChart3 className={className} />,
    Zap: <Zap className={className} />,
    Award: <Award className={className} />,
    Star: <Star className={className} />,
    Eye: <Eye className={className} />,
    Sparkles: <Sparkles className={className} />,
    Home: <Home className={className} />,
    GraduationCap: <GraduationCap className={className} />,
    TrendingUp: <TrendingUp className={className} />,
    Shield: <Shield className={className} />,
    Play: <Play className={className} />,
    RotateCcw: <RotateCcw className={className} />,
    Hash: <Hash className={className} />,
    Timer: <Timer className={className} />,
    CircleCheck: <CircleCheck className={className} />,
    CircleX: <CircleX className={className} />,
    Minus: <Minus className={className} />,
    FileQuestion: <FileQuestion className={className} />,
    Layers: <Layers className={className} />,
    PenLine: <PenLine className={className} />,
    Flag: <Flag className={className} />,
  };

  return <>{icons[name] || <BookOpen className={className} />}</>;
};
